language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

matrix:
  fast_finish: true

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev
